title: LTH Challenge
description: A yearly individual programming competition at LTH organized by <a href="https://codeatlth.org">Code@LTH</a>. Aimed towards university and high school students.
theme: jekyll-theme-minimal
google_analytics: UA-109157638-1
logo: /assets/images/code-logo-transparent.png

collections:
  contests:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
