title: LTH Challenge
description: A yearly programming competition at LTH organized by <a href="https://codeatlth.org">Code@LTH</a>.
theme: jekyll-theme-minimal
google_analytics: UA-109157638-1
logo: /assets/images/code-logo-transparent.png
